version: '3.9'

services:
  webserver:
    build: 
      context: ./frontend
    # container_name: web
    image: webserver
    hostname: webserver
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    # links:
    #   - api