apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: trongminhjr/tracking-position-simulator:v2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice