---
- name: Node exporter container.
  community.docker.docker_container:
    name: minhlt-nodeexporter
    image: prom/node-exporter:latest
    state: started
    restart_policy: "unless-stopped"
    # restart: true
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'


- name: Cadvisor container.
  community.docker.docker_container:
    name: minhlt-cadvisor
    image: gcr.io/cadvisor/cadvisor-arm64:v0.47.0
    restart_policy: "unless-stopped"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /dev/disk/:/dev/disk:ro

      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    #restart: true
    ports:
      - 8080:8080

- name: Prometheus container
  community.docker.docker_container:
    name: minhlt-prometheus
    image: prom/prometheus-linux-arm64
    restart_policy: "unless-stopped"
    volumes:
      - "../roles/monitoring/files/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # - '--enable-feature=expand-external-labels'
      # - '--web.enable-lifecycle'
    restart: true
    ports:
      - 9090:9090

