apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: trongminhjr/tracking-webapp:v2
        # image: test-webapp-tracking
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice